### ISSUE TITLE
Union type parameter reflections are broken in scope methods

### ISSUE THREAD

**Issue by mycarrysun** [barryvdh/laravel-ide-helper#1129]
### Versions:
- ide-helper Version: 2.8.2
- Laravel Version: 8.18.1
- PHP Version: 8.0.0

### Description:
When using union return types, `php artisan ide-helper:models` does not work and produces this error:
```
Call to undefined method ReflectionUnionType::isBuiltin()
```

### Steps To Reproduce
```php
class Contact extends Model {}

class User extends Model
{
  public function contacts(): \Illuminate\Database\Eloquent\Relations\HasMany|Contact
  {
    return $this->hasMany(Contact::class);
  }
}
```

Run `php artisan ide-helper:models` and you will get:
```bash
Exception: Call to undefined method ReflectionUnionType::isBuiltin()
Could not analyze class App\Models\User.

Trace:
#0 /home/mike/PhpstormProjects/prospect-infinity/api/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(980): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->getReturnTypeFromReflection()
#1 /home/mike/PhpstormProjects/prospect-infinity/api/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(527): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->getReturnType()
#2 /home/mike/PhpstormProjects/prospect-infinity/api/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(277): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->getPropertiesFromMethods()
#3 /home/mike/PhpstormProjects/prospect-infinity/api/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(159): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->generateDocs()
#4 /home/mike/PhpstormProjects/prospect-infinity/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->handle()
#5 /home/mike/PhpstormProjects/prospect-infinity/api/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /home/mike/PhpstormProjects/prospect-infinity/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#7 /home/mike/PhpstormProjects/prospect-infinity/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#8 /home/mike/PhpstormProjects/prospect-infinity/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\Container\BoundMethod::call()
#9 /home/mike/PhpstormProjects/prospect-infinity/api/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#10 /home/mike/PhpstormProjects/prospect-infinity/api/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute()
#11 /home/mike/PhpstormProjects/prospect-infinity/api/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#12 /home/mike/PhpstormProjects/prospect-infinity/api/vendor/symfony/console/Application.php(971): Illuminate\Console\Command->run()
#13 /home/mike/PhpstormProjects/prospect-infinity/api/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#14 /home/mike/PhpstormProjects/prospect-infinity/api/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun()
#15 /home/mike/PhpstormProjects/prospect-infinity/api/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run()
#16 /home/mike/PhpstormProjects/prospect-infinity/api/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#17 /home/mike/PhpstormProjects/prospect-infinity/api/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#18 {main}
```

**Comment by mfn** [comment]
PRs welcome!

**Comment by def-studio** [comment]
> PRs welcome!

@mfn I've submitted a PR proposing a solution, but I'm contributing OSS projects since a couple of months only, so I would need a review and some help with tests

**Comment by mycarrysun** [comment]
I actually made a couple tweaks to my model and somehow the error went away - and have not been able to figure out the exact change :facepalm: if it pops up again I will try and nail down the exact conditions needed to repro since I have a feeling this bare bones example might actually not produce the error (even though it was basically the same as what I had in my model).

**Comment by mycarrysun** [comment]
@def-studio nice work on that PR! Thank you for taking the time. Were you able to nail down the exact cause of the error? Was it having union types in both a parameter and return type in the same method?

**Comment by mycarrysun** [comment]
Update after working some more on my project - it looks like the error is only happening when adding a union type parameter to a scope method. So I think the updates will work in #1132 since they are testing union typed parameters in a scope method. :tada:

**Comment by def-studio** [comment]
> @def-studio nice work on that PR! Thank you for taking the time. Were you able to nail down the exact cause of the error? Was it having union types in both a parameter and return type in the same method?

@mycarrysun the cause of the error was the new `ReflectionUnionType` added in php8

basically `ReflectionUnionType` is a wrapper for `ReflectionNamedType` when there is a union type declaration (both in parameter and in method return type)

this one:

```
public function foo(int $param): int{
    return $param;
}
```

will result in `ReflectionNamedType` for both parameter and return type


this one:

```
public function foo(int|float $param): float{
    return (float)$param;
}
```

will result in:

- parameter → ReflectionUnionType
in this case you can retrieve each named types with
`$reflectionUnionType->getTypes() // [ReflectionNamedType => int, ReflectionNamedType => float]`

- return type → ReflectionNamedType


Because of `ReflectionUnionType` lacking of `isBuiltin()` method, an exception was thrown

**Comment by mycarrysun** [comment]
@def-studio excellent explanation! That sounds great. Thanks again for the help with the PR.

**Comment by mfn** [comment]
Should be fixed via https://github.com/barryvdh/laravel-ide-helper/pull/1132 and released via https://github.com/barryvdh/laravel-ide-helper/releases/tag/v2.9.1

**Comment by JorisDebonnet** [comment]
Strange. I installed 2.9.3, but still have this issue 🤔

In my case, I created a `app/helpers.php` file, autoloaded via composer, which includes for example this function signature: 
```php
function array_keys_translate(array $array, array $key_map): array|false
{
    // ...
}
```
Is this a different case than the one solved by this PR, maybe because it's not a class method but a separate helper function? Should I create a new bug report? 😄
