### ISSUE TITLE
Duplicate property creation every time it runs

### ISSUE THREAD

**Issue by faytekin** [barryvdh/laravel-ide-helper#1420]
### Versions:
- ide-helper Version: v2.13.0
- Laravel Version: v9.52.0
- PHP Version: 8.2

### Description:
After updating to the latest version, every time I run the `php artisan ide-helper:models --write` command, the `property-read` in the model is added again, causing duplicate values in the model.

```
/**
 * App\Models\Branch
 *
 * @property int $id
 * @property int $company_id
 * @property string $name
 * @property string|null $phone
 * @property bool $active
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection<int, \App\Models\QrMenu> $activeQrMenus
 * @property-read int|null $active_qr_menus_count
 * @property-read \Illuminate\Database\Eloquent\Collection<int, User> $admins
 * @property-read int|null $admins_count
 * @property-read \App\Models\Company $company
 * @method static \Database\Factories\Company\BranchFactory factory($count = null, $state = [])
 * @method static \Illuminate\Database\Eloquent\Builder|Branch newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Branch newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Branch query()
 * @property-read \Illuminate\Database\Eloquent\Collection<int, \App\Models\QrMenu> $activeQrMenus
 * @property-read \Illuminate\Database\Eloquent\Collection<int, User> $admins
 * @mixin \Eloquent
 */
```

The `activeQrMenus` and `admins` values ​​here are repeating.

There are many models in the project, but this error only occurs in 5 models.

**Comment by DarkStoorM** [comment]
Same issue. However, I found, that `use_generics_annotations` set to `true` will produce duplicates like this

I ran it three times with this setting and it always seem to duplicate the `@property-read` from `HasApiTokens` and `Notifiable` in my default User model. Switching the generics annotations off fixes this issue (requires deleting the previous model docBlock)

```diff
* @property-read \Illuminate\Notifications\DatabaseNotificationCollection<int, \Illuminate\Notifications\DatabaseNotification> $notifications
* @property-read \Illuminate\Database\Eloquent\Collection<int, \Laravel\Sanctum\PersonalAccessToken> $tokens
+* @property-read \Illuminate\Notifications\DatabaseNotificationCollection<int, \Illuminate\Notifications\DatabaseNotification> $notifications
+* @property-read \Illuminate\Database\Eloquent\Collection<int, \Laravel\Sanctum\PersonalAccessToken> $tokens
+* @property-read \Illuminate\Notifications\DatabaseNotificationCollection<int, \Illuminate\Notifications\DatabaseNotification> $notifications
+* @property-read \Illuminate\Database\Eloquent\Collection<int, \Laravel\Sanctum\PersonalAccessToken> $tokens
```

---

Related block:

https://github.com/barryvdh/laravel-ide-helper/blob/4dc20b028adaeadf603860f179f09da5aa21f5b5/src/Console/ModelsCommand.php#L748

Both mentioned traits indeed extend from `Relation`, so maybe it just can't match the correct type for collections of those relations.

**Comment by matthiastjong** [comment]
+1 on this issue

**Comment by matthiastjong** [comment]
FYI I needed to fix this because it caused my CI to fail every time. How I fixed is by changing the command to `php artisan ide-helper:models --no-interaction --write --reset`. The `--reset` flag resets the lookup and re-populates the models.

**Comment by reachuniversal** [comment]
+1, having the same issue

**Comment by jorycn** [comment]
+1 on this issue

**Comment by faytekin** [comment]
> I acknowledge this seems buggy, so we definitely appreciate if someone steps up and looks into fixing this.
> 
> Btw, for those affected: can you use `--reset`?
> 
> (I realized I'm not affected by this bug, because my pipeline uses `ide-helper:models --write --reset`)

I can't use `--reset` because I've defined some model getters using Laravel's [Attribute](https://laravel.com/docs/10.x/eloquent-mutators#defining-an-accessor), and when I add `--reset`, it deletes the manually added properties.

**Comment by Mark-van-Seeters-LW** [comment]
+1 on this, using the reset switch helps but it's quite annoying

**Comment by JeRabix** [comment]
![image](https://user-images.githubusercontent.com/46298617/230670766-0a298e66-ddcc-43b4-aef3-4120afe62ffc.png)
![image](https://user-images.githubusercontent.com/46298617/230670815-f614ef29-5a0e-4027-94c9-f37306baa0b4.png)

Not work with generic types?

**Comment by JeRabix** [comment]
In latest version [phpDocumentor/ReflectionDocBlock](https://github.com/barryvdh/ReflectionDocBlock) generic type parsed correctly, but this package use fork [barryvdh/ReflectionDocBlock](https://github.com/barryvdh/ReflectionDocBlock) and this fork can't parse generic type in DocBlock correcly. So need update fork package, maybe).

**Comment by JeRabix** [comment]
I create PR to fork repository

https://github.com/barryvdh/ReflectionDocBlock/pull/14

**Comment by JeRabix** [comment]
@barryvdh can you help please?)

**Comment by QuentonLuminateOne** [comment]
Running into this issue too:

``` 
* @property-read \Illuminate\Database\Eloquent\Collection<int, \Laravel\Sanctum\PersonalAccessToken> $tokens
* @property-read \Illuminate\Database\Eloquent\Collection<int, \Laravel\Sanctum\PersonalAccessToken> $tokens
*/
class User extends Authenticatable {
}

**Comment by classicalguss** [comment]
Same problem here. Just a  bit of knowledge since it's not mentioned in this thread. In my case, it only happens if there was something "irregular" with the naming convention.

For example the model is User but the relation is called admins. Or if it's two words like payment_logs. Or if it's 1 word, but you're not using standard column naming like user_id for a foreign key on users

**Comment by faytekin** [comment]
Hello @mfn,

The bug located here: https://github.com/barryvdh/ReflectionDocBlock/pull/14, has been successfully corrected with this pull request. If possible, I kindly request you to release a new version incorporating these fixes.

**Comment by raymadrona** [comment]
Still encounter this error even though I upgraded to dev:master.

**Comment by faytekin** [comment]
> Still encountered this error even though I upgraded to dev:master.

The issue was resolved in the `barryvdh/ReflectionDocBlock` package to which this package is linked. If this package updates its dependencies and releases a new version, the problem will be solved.

**Comment by tayeke** [comment]
+1 can we get that dependency updated?

**Comment by barryvdh** [comment]
Tagged

**Comment by faytekin** [comment]
https://github.com/barryvdh/ReflectionDocBlock/compare/v2.1.0...v2.1.1 fixed here.
